create table IF NOT EXISTS USERS
(
    id              bigint generated by default as identity,
    creator_user_id varchar(255) unique,
    name            varchar(255),
    password        varchar(255),
    reg_no          varchar(255),
    primary key (id)
);

create table IF NOT EXISTS USERS_TAXATION
(
    id                 bigint generated by default as identity,
    user_id            bigint         not null,
    name               varchar(100),
    total_income       decimal(15, 2) not null,
    tax_credits_amount decimal(15, 2) not null
);

create table IF NOT EXISTS USERS_TAXATION_DEDUCTIONS
(
    id             bigint generated by default as identity,
    user_id        bigint      not null,
    deduction_type varchar(50) not null
);

create table IF NOT EXISTS USERS_TAXATION_PENSION_DEDUCTIONS
(
    id           bigint generated by default as identity,
    deduction_id bigint         not null,
    "month"        date           not null,
    amount       decimal(15, 2) not null
);

create table IF NOT EXISTS USERS_TAXATION_CREDIT_CARD_DEDUCTIONS
(
    id           bigint generated by default as identity,
    deduction_id bigint         not null,
    "month"        int            not null,
    "year"         int            not null,
    amount       decimal(15, 2) not null
);